### ISSUE TITLE
Enregistrer les identifiants

### ISSUE THREAD

**Issue by dimtion** [B4rb3rouss/shaarlyp#1]
Je trouve que c'est extrêmement redondant de re-rentrer ses identifiants à chaque appel. Selon toi vaut-il mieux faire un wrapper, ou par exemple modifier le script pour mettre des identifiants par défaut ?

Bon j'imagine que c'est plus un outil pour être appelé à partir d'autres programmes, du coups ça dépend où l'on sauvegarde ses crédits.

Et merci pour cet outil !

**Comment by B4rb3rouss** [comment]
C'est exactement ça : c'est prévu pour être appelé à partir d'autres programmes.
Rien ne t'empêche de l'appeler via un alias ou un script, qui contient tes identifiants : 

```
alias shaarlyp='python3 /chemin/vers/shaarlyp identifiant mdp'
```

**Comment by dimtion** [comment]
D'accord, merci :)
